1  spring.application.name=genify-backend
2
3  spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/genify}
4  spring.datasource.username=${DATABASE_USERNAME:postgres}
5  spring.datasource.password=${DATABASE_PASSWORD}
6
7  spring.jpa.hibernate.ddl-auto=update
8  spring.jpa.show-sql=true
9  spring.jpa.properties.hibernate.format_sql=true
10 server.port=${PORT:8081}